service: minecraft-ecs

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  logRetentionInDays: 90

functions:
  status:
    handler: handler.status

resources:
  - ${file(resources/vpc.yml)}
  - ${file(resources/ecs.yml)}
  - ${file(resources/helloworld.yml)}
