service: minecraft-ecs
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    authorizers:
      mgmtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt [ UserPool, ProviderURL ]
        audience:
          - Ref: UserPoolClient
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'ecs:DescribeServices'
        - 'ecs:ListServices'
        - 'elasticloadbalancing:DescribeTargetGroups'
        - 'elasticloadbalancing:DescribeLoadBalancers'
        - 'elasticloadbalancing:DescribeListeners'
      Resource: '*'

functions:
  status:
    handler: handlers/status.handler
    environment:
      CLUSTER_NAME: !Ref EcsCluster
    events:
      - httpApi:
          method: 'GET'
          path: /
          authorizer:
            name: mgmtAuthorizer

resources:
  - ${file(resources/vpc.yml)}
  - ${file(resources/ecs.yml)}
  - ${file(resources/cognito.yml)}
  - ${file(resources/helloworld.yml)}

plugins:
  - serverless-offline
