service: minecraft-ecs

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello

resources:
  - ${file(resources/vpc.yml)}
  - ${file(resources/ecs.yml)}
  - ${file(resources/helloworld.yml)}
