Parameters:
  WorldName:
    Type: String
    Description: Name of the Minecraft World
    Default: "helloworld"
  OperatorUsername:
    Type: String
    Description: The username of the main operator for this world
    Default: ""
  CpuUnits:
    Type: Number
    Description: Fargate CPU units to consume (1024 or 2048 recommended)
    Default: 1024
  Memory:
    Type: Number
    Description: The amount (in MiB) of memory used by the task (between 4096 and 8192 recommended)
    Default: 4096
  ListenPort:
    Type: Number
    Description: The TCP port for the load balancer to listen to for connections (needs to be unique)
    Default: 25565

Resources:
  HelloWorldBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - "-"
          - - minecraftecs
            - ${sls:stage}
            - !Ref WorldName
      Tags:
        - Key: STAGE
          Value: ${sls:stage}
        - Key: MINECRAFT
          Value: !Ref WorldName

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name:
        Fn::Join:
          - "-"
          - - minecraft-lb
            - ${sls:stage}
            - !Ref WorldName
      VpcId: !Ref FargateVPC
      Port: 25565
      HealthCheckEnabled: true
      IpAddressType: ipv4
      Protocol: TCP
      TargetType: ip
      Tags:
        - Key: STAGE
          Value: ${sls:stage}
        - Key: MINECRAFT
          Value: !Ref WorldName

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref ListenPort
      Protocol: TCP

  HelloWorldTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: minecraftecs-${sls:stage}
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref CpuUnits
      Memory: !Ref Memory
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name:
            Fn::Join:
              - "-"
              - - minecraftecs
                - server
                - ${sls:stage}
                - !Ref WorldName
          Image: ghcr.io/deckerego/minecraft-ecs/minecraft-server:latest
          PortMappings:
              - ContainerPort: 25565
                HostPort: 25565
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: mc
          Command:
            - Fn::Join:
              - "/"
              - - "s3:/"
                - Ref: HelloWorldBucket
            - !Ref WorldName
            - !Ref OperatorUsername
          HealthCheck:
            Command:
              - "CMD-SHELL"
              - "cat /proc/net/tcp | grep 63DD"
            StartPeriod: 300
      Tags:
        - Key: STAGE
          Value: ${sls:stage}
        - Key: MINECRAFT
          Value: !Ref WorldName

  HelloWorldTaskService:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListener
    Properties:
      ServiceName:
        Fn::Join:
          - "-"
          - - minecraftecs
            - service
            - ${sls:stage}
            - !Ref WorldName
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref HelloWorldTaskDefinition
      EnableECSManagedTags: true
      DesiredCount: 0
      LaunchType: FARGATE
      PlatformVersion: 1.3.0
      LoadBalancers:
        - ContainerName:
            Fn::Join:
              - "-"
              - - minecraftecs
                - server
                - ${sls:stage}
                - !Ref WorldName
          ContainerPort: 25565
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet
          SecurityGroups:
            - !Ref MinecraftSecurityGroup
      Tags:
        - Key: STAGE
          Value: ${sls:stage}
        - Key: MINECRAFT
          Value: !Ref WorldName
